### ISSUE TITLE
Wikibase extension broken since AJV de-minification

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5258]
This issue seems to have been introduced by #5252. Sorry about the hasty merge!

### To Reproduce
1. Run OpenRefine from the master branch (`./refine clean && ./refine`) and open a project
2. Observe that the Wikibase extension does not show up

### Current Results
```
Uncaught TypeError: (intermediate value)(...) is not a function
    <anonymous> http://127.0.0.1:3333/project-bundle.js:54094

```
This is a location in ajv's code.

### Screenshots

![image](https://user-images.githubusercontent.com/309908/190469977-a696b947-6ac5-4b2f-9e9d-b7c61e390631.png)

### Versions

 - Browser Version: Firefox 91.13.0esr
 - OpenRefine: master branch

### Additional context
Discovered by @Abbe98

**Comment by elebitzero** [comment]
@wetneb

I tested the ajv.js that replaced the avj.min.js. The Wikidata extension was loading fine on Chrome & Firefox on Windows 10.  AJV is used for parsing the wiki manifests so I also added all the sample manifests, and that was working.

As a result, I'm confused why you are seeing this error.

I just rechecked my branch (elebitzero:minified-ajv-cleanup), and it is still working for me.

The version of ajv.js is 6.12.3, the same as that of the ajv.min.js.

I googled `Uncaught TypeError: (intermediate value)(...) is not a function`, and it seems the issue may be due to a missing semi-colon.

I would like to fix whatever the issue is since this is the last minified JS file in the project, but if I can't reproduce the problem, I won't be able to fix it.

More details would be helpful, like if this was on MacOs or Linux?

As an aside, this does raise the point that we don't have any Cypress tests on the Wikidata extension.  @fgiroud created a draft 2 years ago.  I'll look at that to see if I can get at least some basic tests added, since this is a blind spot in the test automation.

**Comment by elebitzero** [comment]
@wetneb

I also noticed in the screenshot the extensions menu has 'Named-entity recognition'.  Is that some new extension and does it use AJV?  I'm wondering if that has something to do with it.

**Comment by wetneb** [comment]
This was on Linux.

> I also noticed in the screenshot the extensions menu has 'Named-entity recognition'. Is that some new extension and does it use AJV? I'm wondering if that has something to do with it.

That extension does not use AJV.

Since that is not reproduciible on your side I can try to investigate more on mine in the coming days.

**Comment by wetneb** [comment]
I can also reproduce this on your original branch (`elebitzero:minified-ajv-cleanup`, so before merging), with both Chromium and Firefox, and without the NER extension.

Could this be due to some leftover minified code at the beginning of the file?
https://github.com/OpenRefine/OpenRefine/pull/5252/files#r972730044

**Comment by elebitzero** [comment]
Thank you for looking into this.  I checked and the ajv.js file is correct.  I think the minified-looking part at the top has to do with support for ES modules. 

I'll have to look into it further.  It is strange that it works on Windows but not Linux.
