### ISSUE TITLE
Stuck With Setup With Environment

### ISSUE THREAD

**Issue by mipa1304** [OpenRefine/OpenRefine#2319]
error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
:ReactNative:Unexpected empty result of running '[node, undefined, config]' command.
:ReactNative:Running '[node, undefined, config]' command failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\vmpat\teacherApp\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 170

* What went wrong:
A problem occurred evaluating script.
> internal/modules/cjs/loader.js:985  throw err;  ^Error: Cannot find module 'C:\Users\vmpat\teacherApp\android\undefined'    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
 at Function.Module._load (internal/modules/cjs/loader.js:864:27)
 at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)    at internal/main/run_main_module.js:18:47 {  code: 'MODULE_NOT_FOUND',  requireStack: []}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 943ms

    at checkExecSyncError (child_process.js:630:11)
    at execFileSync (child_process.js:648:15)
    at runOnAllDevices (C:\Users\vmpat\teacherApp\node_modules\react-native\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.handleAction (C:\Users\vmpat\teacherApp\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:164:9)
PS C:\Users\vmpat\teacherApp> npx react-native run-android
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
  - react-native-splash-screen (to unlink run: "react-native unlink
react-native-splash-screen")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your
app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1205 file(s) to forward-jetify. Using 4 workers...
info Starting JS server...
info Launching emulator...
error Failed to launch emulator. Reason: Emulator exited before boot..
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...
:ReactNative:Unexpected empty result of running '[node, undefined, config]' command.
:ReactNative:Running '[node, undefined, config]' command failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\vmpat\teacherApp\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 170

* What went wrong:
A problem occurred evaluating script.
> internal/modules/cjs/loader.js:985  throw err;  ^Error: Cannot find module 'C:\Users\vmpat\teacherApp\android\undefined'    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
 at Function.Module._load (internal/modules/cjs/loader.js:864:27)
 at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)    at internal/main/run_main_module.js:18:47 {  code: 'MODULE_NOT_FOUND',  requireStack: []}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
:ReactNative:Unexpected empty result of running '[node, undefined, config]' command.
:ReactNative:Running '[node, undefined, config]' command failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\vmpat\teacherApp\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 170

* What went wrong:
A problem occurred evaluating script.
> internal/modules/cjs/loader.js:985  throw err;  ^Error: Cannot find module 'C:\Users\vmpat\teacherApp\android\undefined'    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
 at Function.Module._load (internal/modules/cjs/loader.js:864:27)
 at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)    at internal/main/run_main_module.js:18:47 {  code: 'MODULE_NOT_FOUND',  requireStack: []}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

    at checkExecSyncError (child_process.js:630:11)
    at execFileSync (child_process.js:648:15)
    at runOnAllDevices (C:\Users\vmpat\teacherApp\node_modules\react-native\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.handleAction (C:\Users\vmpat\teacherApp\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:164:9)

**Comment by wetneb** [comment]
Hi @mipa1304, this looks completely unrelated to OpenRefine. Did you mix up repositories?
