### ISSUE TITLE
OpenRefine does not build on Macos X 10.8.5

### ISSUE THREAD

**Issue by daboe01** [OpenRefine/OpenRefine#822]
Daniel:~ daboe01$ cd /Users/daboe01/Downloads/OpenRefine-master 
Daniel:OpenRefine-master daboe01$ ./refine build
Buildfile: /Users/daboe01/Downloads/OpenRefine-master/build.xml

build_server:

build_webapp:
    [javac] Compiling 372 source files to /Users/daboe01/Downloads/OpenRefine-master/main/webapp/WEB-INF/classes
    [javac] /Users/daboe01/Downloads/OpenRefine-master/main/src/com/google/refine/browsing/facets/ScatterplotFacet.java:396: cannot find symbol
    [javac] symbol  : method encodeBase64String(byte[])
    [javac] location: class org.apache.commons.codec.binary.Base64
    [javac]         String encoded = Base64.encodeBase64String(output.toByteArray());
    [javac]                                ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 1 error

BUILD FAILED
/Users/daboe01/Downloads/OpenRefine-master/build.xml:134: Compile failed; see the compiler error output for details.

Total time: 6 seconds
Error while running ant task 'build'
Daniel:OpenRefine-master daboe01$
